// <auto-generated />
using System;
using Assignment4.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment4.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment4.Models.EF_Models+Results", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("accCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("likesCount")
                        .HasColumnType("int");

                    b.Property<string>("schoolCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schoolName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schoolUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("studentSize")
                        .HasColumnType("int");

                    b.Property<int?>("tuitionOutState")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Assignment4.Models.EF_Models+SignUp", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("email");

                    b.ToTable("SignUp");
                });
#pragma warning restore 612, 618
        }
    }
}
